# Generated by Django 4.2.6 on 2023-11-15 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=250)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('car_model', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('fabrication', models.PositiveSmallIntegerField()),
                ('fuel', models.CharField(max_length=16)),
                ('engine', models.CharField(max_length=128)),
                ('transmission', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('doors', models.CharField(max_length=16)),
                ('co2_emissions_combined', models.CharField(max_length=32)),
                ('features', models.CharField(max_length=128)),
                ('other_parameters', models.CharField(max_length=128)),
                ('safety', models.CharField(max_length=128)),
                ('comfort', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='cars_brand_images', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Carcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.car')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_images', verbose_name='Изображение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.car')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.car')),
            ],
        ),
    ]
