# Generated by Django 4.2.6 on 2023-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
