# Generated by Django 4.2.6 on 2023-12-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_car_max_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
