# Generated by Django 4.2.6 on 2023-12-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_subscriber_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars_images')),
                ('duration', models.DurationField()),
                ('link', models.URLField()),
            ],
        ),
    ]
